sudo: required

language: sh

git:
  lfs_skip_smudge: true

before_install:
    - sudo apt-get update && sudo apt-get install -y shellcheck

script:
  - ls -l
  - bash test.sh
  - bash assignment-04/code/task1.sh -h
  - ls -l Assets/shell_test/test1/
  - bash assignment-04/code/task1.sh -f Assets/shell_test/test1/ -r 50 -t "CUC"
  - ls -l Assets/shell_test/test1/
  - bash assignment-04/code/task2.sh -h
  - bash assignment-04/code/task2.sh -i
  - bash assignment-04/code/task2.sh -a
  - bash assignment-04/code/task2.sh -b
  - bash assignment-04/code/task2.sh -c
  - bash assignment-04/code/task2.sh -d
  - bash assignment-04/code/task2.sh -e
  - bash assignment-04/code/task3.sh -h
  - bash assignment-04/code/task3.sh -i
  - bash assignment-04/code/task3.sh -a
  - bash assignment-04/code/task3.sh -b
  - bash 0assignment-04/code/task3.sh -c
  - bash assignment-04/code/task3.sh -d
  - bash assignment-04/code/task3.sh -e
  - bash assignment-04/code/task3.sh -u "/ksc.html"
  - bash assignment-04/code/task3.sh -u "/"

after_script:
  - /usr/bin/shellcheck test.sh
  - /usr/bin/shellcheck assignment-04/code/task1.sh
  - /usr/bin/shellcheck assignment-04/code/ask2.sh
  - /usr/bin/shellcheck assignment-04/code/task3.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

after_success:
  - cd Assets
  - git add .
  - git commit -m "Travis Image Test"
  - git push origin master -f
  - cd ..

notifications:
  email:
    on_success: never
